# Travis continuous integration for kitodo-production

language: java

cache:
  directories:
    - $HOME/.m2
  timeout: 1000

dist: xenial

jdk:
  - openjdk8

addons:
  chrome: stable

env: DB=mysql

services:
  - mysql

script:
  - travis_wait 30 mvn clean install -B '-Pall-tests,flyway,checkstyle,findbugs,!development' && xvfb-run --server-args="-screen 0 1600x1280x24" mvn clean install -B '-Pselenium,!development'

# install: true is deactivating the separate install-step, which runs before the script
install: true

before_install:

before_script:
  - cp config/database.yml.travis config/database.yml
  - cp Kitodo-DataManagement/src/main/resources/db/config/flyway.properties.travis Kitodo-DataManagement/src/main/resources/db/config/flyway.properties
  - sudo mysql_upgrade -u root
  - sudo service mysql restart
  - mysql -u root -e 'CREATE DATABASE kitodo;'
  - mysql -u root -e "CREATE USER 'kitodo'@'localhost' IDENTIFIED BY 'kitodo';"
  - mysql -u root -e "GRANT ALL ON kitodo.* TO 'kitodo'@'localhost';"
  - mysql -u root kitodo < Kitodo/setup/schema.sql
  - mysql -u root kitodo < Kitodo/setup/default.sql
  - export MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
